/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ArrayStatisticsTest {

    private final ArrayStatistics stats = new ArrayStatistics();
    private final int[] data = {5, 10, 3, 8, 2};

    /* ===== FOR LOOP TESTS ===== */

    @Test
    void testMaximumUsingForLoop() {
        assertEquals(10, stats.maximumUsingForLoop(data));
    }

    @Test
    void testMinimumUsingForLoop() {
        assertEquals(2, stats.minimumUsingForLoop(data));
    }

    @Test
    void testSumUsingForLoop() {
        assertEquals(28, stats.sumUsingForLoop(data));
    }

    @Test
    void testAverageUsingForLoop() {
        assertEquals(5, stats.averageUsingForLoop(data)); // integer division
    }

    /* ===== STREAM TESTS ===== */

    @Test
    void testMaximumUsingStream() {
        assertEquals(10, stats.maximumUsingStream(data));
    }

    @Test
    void testMinimumUsingStream() {
        assertEquals(2, stats.minimumUsingStream(data));
    }

    @Test
    void testSumUsingStream() {
        assertEquals(28, stats.sumUsingStream(data));
    }

    @Test
    void testAverageUsingStream() {
        assertEquals(5, stats.averageUsingStream(data)); // integer division
    }
}
